name: run test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install gettext
      run: sudo apt install gettext -y

    - name: Configure
      run: mkdir -p build && cd build && ../configure

    - name: Bbuild
      run: make -C build

    - name: Install
      run: sudo make install -C build

    - name: Test
      run: ./test.sh
