name: run test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: build
      run: make

    - name: install
      run: sudo make install

    - name: test
      run: ./test.sh
